name: Slack notify

on:
  push:
    branches: [ master ]

jobs:
  notify-success:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Succeeded Check
      uses: 8398a7/action-slack@v3
      with:
        status: success
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

    - name: Failed Check
      uses: 8398a7/action-slack@v3
      with:
        status: failure
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
    
    - name: Cancelled Check
      uses: 8398a7/action-slack@v3
      with:
        status: cancelled
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
