name: Slack notify

on:
  push:
    branches: [ master ]

jobs:
  notify-success:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo Hello, world!

    - name: Notify using 8398a7 library
      uses: 8398a7/action-slack@v3.0.2
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      with:
        status: ${{ job.status }}
        author_name: 'Build and Push images'
        fields: commit,message,workflow,repo
